[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "braandket-synthesis"
version = "0.2.1"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
description = "A library for quantum circuit synthesis based on BraAndKet."
readme = "README.md"

requires-python = ">=3.7"
dependencies = ["braandket>=0.8.0"]


[tool.setuptools]
package-dir = { "" = "src" }
packages.find.where = ["src"]
