[tool.poetry]
name = "np-logging"
version = "0.5.1"
description = "Pre-configured file, web, and email logging for Mindscope neuropixels projects, repackaging code from AIBS mpeconfig."
authors = [
    "Ben Hardcastle <ben.hardcastle@alleninstitute.org>",
    "Ross Hytnen <rossh@alleninstitute.org>", 
    "Ben Sutton <ben.sutton@alleninstitute.org>",
]
maintainers = ["Ben Hardcastle <ben.hardcastle@alleninstitute.org>"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
packages = [{include = "np_logging", from = "src"}]

[tool.poetry.urls]
"Repository" = "https://github.com/alleninstitute/np_logging"
"Bug Tracker" = "https://github.com/alleninstitute/np_logging/issues"

[tool.poetry.dependencies]
python = "^3.7"
np_config = ">0.4.12"
importlib_resources = ">1.4"

[tool.poetry.group.dev.dependencies]
pip-tools = "*"
isort = "*"
mypy = "*"
black = "*"
pytest = "*"
coverage = {extras = ["toml"], version = "^7.1.0"}
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "--doctest-modules",
    # "--pdb",
    # "--pdbcls=IPython.terminal.debugger:TerminalPdb",
]

doctest_optionflags = [
    "NORMALIZE_WHITESPACE",
    "IGNORE_EXCEPTION_DETAIL",
    "ELLIPSIS",
]

testpaths = [
    "tests",
    "src",
]

[tool.coverage.paths]
source = ["src"]

[tool.coverage.run]
branch = true
source = ["np_logging"]

[tool.coverage.report]
show_missing = true