[tool.poetry]
name = "spryfox-assessment-tc"
version = "0.1.0"
description = ""
authors = ["Tiziano Cocci√≤ <tiziano.coccio@gmail.com>"]
packages = [{include = "tasks"}]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "1.5.3"
matplotlib = "3.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
