

[tool.poetry]
name = "colorbymood"
version = "0.2.1"
description = ""
authors = ["Niels Maedern <maedern@student.ethz.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
matplotlib = "^3.7.0"
pyqt6 = "^6.4.2"
pyyaml = "^6.0"
click = "^8.1.3"

[tool.poetry.scripts]
colorbymood = 'colorbymood.cli:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
