[build-system]
requires = ["setuptools", "setuptools_scm[toml]", "wheel"]
build-backend = "setuptools.build_meta"

[project]
authors = [{name = "devforfu", email = "developer.z@outlook.com"}]
classifiers = ["Programming Language :: Python :: 3"]
description = "A package helping to navigate nested structures easily"
dynamic = ["version"]
name = "python-needle"
requires-python = ">=3.9"
dependencies = ["rich"]
readme = "README.md"
urls = {code = "https://github.com/devforfu/needle"}

[project.optional-dependencies]
test = ["pytest"]

[tool.setuptools_scm]
write_to = "needle/_version.py"
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
