[build-system]
requires = ["hatchling","schemawizard_package"]

build-backend = "hatchling.build"

[project]
name = "zetl"
version = "1.0.8"
authors = [
  { name="Dave Skura", email="dskura@gmail.com" },
]
description = "A simple ETL framework for Python, SQL and BAT files which uses a Postgres database for activity logging."
readme = "README.md"
requires-python = ">=3.7"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/daveskura/zetl"
"Author Linkedin" = "https://www.linkedin.com/in/2166883"
